service: notes-app-api

plugins:
 - serverless-webpack
 - serverless-offline
 
custom:
 webpack:
 webpackConfig: ./webpack.config.js
 includeModules: true
provider:
 name: aws
 runtime: nodejs8.10
 stage: prod
 region: us-east-1